# Generated by Django 5.2.8 on 2025-11-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiquest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
